# docker-compose.yml
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
      args:
        # Pass all necessary host IDs to the build
        UID: ${UID}
        GID: ${GID}
        DOCKER_GID: ${DOCKER_GID}
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock