# docker-compose.yml
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
      args:
        # Pass the host's docker group ID to the build
        DOCKER_GID: ${DOCKER_GID}
    user: "${UID}:${GID}" # Run the container as the current host user
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
